# Generated by Django 4.1.4 on 2023-01-11 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Rasm haqida batafsil')),
                ('image', models.ImageField(upload_to='example/', verbose_name='Namuna rasm')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Example photo',
                'verbose_name_plural': 'Example photos',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Ruhsat nomi')),
                ('permission_status', models.BooleanField(choices=[(True, 'Ishga tushirish'), (False, "To'xtatish")], default=True, verbose_name='Xolat')),
            ],
        ),
        migrations.CreateModel(
            name='TelegramUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Ismi va familiya')),
                ('username', models.CharField(blank=True, max_length=40, null=True, verbose_name='Username')),
                ('tg_id', models.CharField(max_length=20, verbose_name='Telegram id')),
                ('chat_id', models.CharField(max_length=20, verbose_name='Chat id')),
                ('request_all_count', models.IntegerField(default=0, verbose_name="Umumiy so'rovlar soni")),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_add', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.telegramuser', verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Xabar')),
                ('create_add', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='robot.telegramuser', verbose_name='User')),
            ],
        ),
    ]
