# Generated by Django 4.1.4 on 2023-03-26 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('robot', '0003_alter_permission_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Permission',
        ),
    ]
